# Generated by Django 5.2.11 on 2026-02-25 10:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_subscription_subscriptio_user_id_2a19e8_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='payment_provider',
            field=models.CharField(choices=[('none', 'None'), ('stripe', 'Stripe (Android)'), ('apple', 'Apple IAP (iOS)'), ('revenuecat', 'RevenueCat')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='subscription',
            name='revenuecat_user_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='subscription',
            name='stripe_customer_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='subscription',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['stripe_subscription_id'], name='subscriptio_stripe__12aa53_idx'),
        ),
    ]
