# Generated by Django 6.0.2 on 2026-02-25 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_subscription_payment_provider_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('FREE', 'Free'), ('PRO', 'Pro'), ('PRO_PLUS', 'Pro Plus')], max_length=10, unique=True)),
                ('monthly_price', models.DecimalField(decimal_places=2, help_text='Monthly price in USD', max_digits=6)),
                ('annual_price', models.DecimalField(decimal_places=2, help_text='Annual price in USD', max_digits=6)),
                ('daily_interview_limit', models.IntegerField(default=1, help_text='Number of mock interviews per day')),
                ('is_active', models.BooleanField(default=True)),
                ('stripe_monthly_price_id', models.CharField(blank=True, default='', max_length=100)),
                ('stripe_annual_price_id', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
            },
        ),
    ]
