# Generated by Django 6.0.2 on 2026-02-22 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_remove_question_category_question_specialization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=50)),
                ('specialization', models.CharField(blank=True, max_length=50)),
                ('icon', models.CharField(default='📚', max_length=10)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='answeroption',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='answeroption',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false', 'True / False'), ('text', 'Short Text')], default='multiple_choice', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='specialization',
            field=models.CharField(blank=True, default='backend', max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='learning.topic'),
        ),
    ]
