# Generated by Django 6.0.2 on 2026-02-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_topic_alter_answeroption_options_answeroption_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='session_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
