# Generated by Django 6.0.2 on 2026-02-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_userprogress_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprogress',
            name='session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
