# Generated by Django 6.0.2 on 2026-02-22 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_alter_userprogress_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='answeroption',
            name='text_en',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='answeroption',
            name='text_uk',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='question',
            name='explanation_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='explanation_uk',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='text_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='text_uk',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='name_en',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='topic',
            name='name_uk',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
