# Generated by Django 6.0.2 on 2026-02-24 18:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_answeroption_text_en_answeroption_text_uk_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['is_active', 'language'], name='learning_qu_is_acti_ba28a0_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['is_active', 'difficulty'], name='learning_qu_is_acti_4350db_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['topic', 'is_active'], name='learning_qu_topic_i_fde409_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['language', 'specialization'], name='learning_qu_languag_4dc45b_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['language', 'is_active'], name='learning_to_languag_72878f_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['is_active', 'order'], name='learning_to_is_acti_02be9d_idx'),
        ),
        migrations.AddIndex(
            model_name='useranswer',
            index=models.Index(fields=['user', 'answered_at'], name='learning_us_user_id_eaaa9c_idx'),
        ),
        migrations.AddIndex(
            model_name='useranswer',
            index=models.Index(fields=['user', 'is_correct'], name='learning_us_user_id_5a73f7_idx'),
        ),
        migrations.AddIndex(
            model_name='useranswer',
            index=models.Index(fields=['question', 'is_correct'], name='learning_us_questio_9e98aa_idx'),
        ),
        migrations.AddIndex(
            model_name='userprogress',
            index=models.Index(fields=['user', 'answered_at'], name='learning_us_user_id_60a3ea_idx'),
        ),
        migrations.AddIndex(
            model_name='userprogress',
            index=models.Index(fields=['user', 'is_correct'], name='learning_us_user_id_3655ff_idx'),
        ),
        migrations.AddIndex(
            model_name='userprogress',
            index=models.Index(fields=['user', 'session_id'], name='learning_us_user_id_a91af8_idx'),
        ),
        migrations.AddIndex(
            model_name='userprogress',
            index=models.Index(fields=['user', 'xp_earned'], name='learning_us_user_id_2f2fb4_idx'),
        ),
        migrations.AddIndex(
            model_name='userprogress',
            index=models.Index(fields=['question', 'user'], name='learning_us_questio_81f214_idx'),
        ),
    ]
