# Generated by Django 6.0.2 on 2026-02-24 18:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='aiusage',
            index=models.Index(fields=['user', 'last_reset'], name='ai_aiusage_user_id_2a24ff_idx'),
        ),
        migrations.AddIndex(
            model_name='aiusage',
            index=models.Index(fields=['last_reset'], name='ai_aiusage_last_re_4bc8e7_idx'),
        ),
    ]
