# Generated by Django 6.0.2 on 2026-02-22 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_dailychallenge_remove_userprofile_last_activity_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('challenge_type', models.CharField(choices=[('answer_questions', 'Answer N Questions'), ('answer_hard', 'Answer N Hard Questions'), ('complete_topic', 'Complete a Topic'), ('ai_interview', 'Do AI Interview Session'), ('streak_protect', 'Answer at least 1 question'), ('perfect_score', 'Get 100% on N questions')], max_length=50)),
                ('language', models.CharField(blank=True, max_length=50)),
                ('difficulty', models.CharField(blank=True, max_length=20)),
                ('goal_count', models.IntegerField()),
                ('bonus_xp', models.IntegerField(default=100)),
                ('icon', models.CharField(default='🏆', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('difficulty_level', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Challenge Template',
                'verbose_name_plural': 'Challenge Templates',
            },
        ),
        migrations.AlterModelOptions(
            name='dailychallenge',
            options={'ordering': ['date', 'order']},
        ),
        migrations.RemoveField(
            model_name='dailychallenge',
            name='bonus_xp',
        ),
        migrations.RemoveField(
            model_name='dailychallenge',
            name='goal_count',
        ),
        migrations.RemoveField(
            model_name='dailychallenge',
            name='goal_type',
        ),
        migrations.RemoveField(
            model_name='dailychallenge',
            name='language',
        ),
        migrations.AddField(
            model_name='dailychallenge',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userdailychallenge',
            name='xp_awarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dailychallenge',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='userdailychallenge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_challenges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='userdailychallenge',
            unique_together={('user', 'challenge')},
        ),
        migrations.AddField(
            model_name='dailychallenge',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gamification.challengetemplate'),
        ),
    ]
