# Generated by Django 6.0.2 on 2026-02-22 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0003_challengetemplate_alter_dailychallenge_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailychallenge',
            unique_together={('date', 'order')},
        ),
    ]
