# Generated by Django 6.0.2 on 2026-02-22 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0004_alter_dailychallenge_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ui_language',
            field=models.CharField(choices=[('en', 'English'), ('uk', 'Українська')], default='en', max_length=5),
        ),
    ]
