# Generated by Django 6.0.2 on 2026-02-24 18:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0005_userprofile_ui_language'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='timezone',
            field=models.CharField(default='UTC', help_text="User's timezone for daily reset calculations", max_length=50),
        ),
        migrations.AddIndex(
            model_name='dailychallenge',
            index=models.Index(fields=['date', 'order'], name='gamificatio_date_c384e7_idx'),
        ),
        migrations.AddIndex(
            model_name='dailychallenge',
            index=models.Index(fields=['date'], name='gamificatio_date_2b41f2_idx'),
        ),
        migrations.AddIndex(
            model_name='streak',
            index=models.Index(fields=['last_activity_date'], name='gamificatio_last_ac_c1266c_idx'),
        ),
        migrations.AddIndex(
            model_name='streak',
            index=models.Index(fields=['user', 'last_activity_date'], name='gamificatio_user_id_c55d84_idx'),
        ),
        migrations.AddIndex(
            model_name='userdailychallenge',
            index=models.Index(fields=['user', 'is_completed'], name='gamificatio_user_id_421a78_idx'),
        ),
        migrations.AddIndex(
            model_name='userdailychallenge',
            index=models.Index(fields=['challenge', 'user'], name='gamificatio_challen_be58c2_idx'),
        ),
        migrations.AddIndex(
            model_name='userdailychallenge',
            index=models.Index(fields=['user', 'completed_at'], name='gamificatio_user_id_95af0e_idx'),
        ),
    ]
