# Generated by Django 6.0.2 on 2026-03-01 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='display_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
